services:
  nodeuidev:
    build: ..
    container_name: nodeui-dev
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      NODE_ENV: "development"
      HUB_ADAPTER_API_URL: "http://localhost:8081"
      BASE_URL: "http://localhost:3000"
      KEYCLOAK_URL: "http://localhost:8080"
      KEYCLOAK_REALM: "flame"
      KEYCLOAK_CLIENT_ID: "node-ui"
      KEYCLOAK_CLIENT_SECRET: "w9sThil4yyMNb4rnG2zuHtKa6EkfxHVV"
      NUXT_OIDC_PROVIDERS_KEYCLOAK_BASE_URL: http://localhost:8080/realms/flame
      NUXT_OIDC_PROVIDERS_KEYCLOAK_CLIENT_ID: node-ui
      NUXT_OIDC_PROVIDERS_KEYCLOAK_CLIENT_SECRET: w9sThil4yyMNb4rnG2zuHtKa6EkfxHVV
    ports:
      - '3000:3000'
    restart: always

  keycloakdb:
    image: postgres
    environment:
      POSTGRES_DB: testkeycloakdb
      POSTGRES_USER: testkeycloakuser
      POSTGRES_PASSWORD: testkeycloakpassword
    restart:
      always

  keycloak:
    # Have to use 22.0.0 for realm import. TODO: figure how to import realm config with 23+
    image: quay.io/keycloak/keycloak:24.0.1
    volumes:
      - ./test-realm.json:/opt/keycloak/data/import/realm-export.json
    command: ["start-dev", "--import-realm"]
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: testkeycloakdb
      DB_USER: testkeycloakuser
      DB_SCHEMA: public
      DB_PASSWORD: testkeycloakpassword
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_USER: keycloakuser
      KEYCLOAK_PASSWORD: keycloakpassword
      PROXY_ADDRESS_FORWARDING: "true"
      KEYCLOAK_LOGLEVEL: DEBUG
    ports:
      - '8080:8080'
    depends_on:
      - keycloakdb
    restart:
      always
