import {
  ServiceCheckStatus,
  ServiceMonitoringStatus,
  type ServiceHealthHistory,
} from "~/services/Api";

export const fakeServiceHealthHistory: ServiceHealthHistory = {
  monitoring_enabled: true,
  monitoring_detail: null,
  interval_seconds: 60,
  retention_days: 30,
  start: "2026-07-30T11:00:00Z",
  end: "2026-07-30T12:00:00Z",
  services: {
    kong: {
      configured: true,
      status: ServiceMonitoringStatus.ACTIVE,
      url: "http://kong:8001/status",
      detail: null,
      total_checks: 60,
      successful_checks: 59,
      failed_checks: 1,
      uptime_percentage: 98.33,
      min_latency_ms: 12,
      avg_latency_ms: 30,
      max_latency_ms: 1204,
      last_status: ServiceCheckStatus.OK,
      last_status_code: 200,
      last_checked_at: "2026-07-30T12:00:00Z",
      last_error: null,
      checks: [],
      checks_returned: 0,
      buckets: [
        {
          start: "2026-07-30T11:00:00Z",
          end: "2026-07-30T11:00:30Z",
          total: 1,
          successful: 1,
          failed: 0,
          max_latency_ms: 25,
          avg_latency_ms: 25,
          worst_status: ServiceCheckStatus.OK,
          message: null,
        },
        {
          start: "2026-07-30T11:00:30Z",
          end: "2026-07-30T11:01:00Z",
          total: 1,
          successful: 0,
          failed: 1,
          max_latency_ms: null,
          avg_latency_ms: null,
          worst_status: ServiceCheckStatus.ERROR,
          message: "Connection refused",
        },
      ],
    },
    fhir: {
      configured: false,
      status: ServiceMonitoringStatus.DISABLED,
      url: null,
      detail: "No URL configured for this service on this node",
      total_checks: 0,
      successful_checks: 0,
      failed_checks: 0,
      uptime_percentage: null,
      min_latency_ms: null,
      avg_latency_ms: null,
      max_latency_ms: null,
      last_status: null,
      last_status_code: null,
      last_checked_at: null,
      last_error: null,
      checks: [],
      checks_returned: 0,
      buckets: [],
    },
  },
};

export const fakeMonitoringDisabled: ServiceHealthHistory = {
  ...fakeServiceHealthHistory,
  monitoring_enabled: false,
  monitoring_detail:
    "Postgres is not configured, service health is not being recorded",
  interval_seconds: null,
  retention_days: null,
  services: {},
};
