name: Docker Preview Images

on:
  push:
    branches-ignore:
      - develop
  pull_request:
    branches:
      - develop
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-edge-image:
    name: Build and push edge Docker image
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Build edge image
        uses: ./.github/actions/build-docker-image
        with:
          platforms: linux/amd64
          docker_file: prod.Dockerfile
          push: 'true'
          token: ${{ secrets.GITHUB_TOKEN }}
          extra_tag: edge

  build-canary-image:
    name: Build and push canary Docker image
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Build canary image
        uses: ./.github/actions/build-docker-image
        with:
          platforms: linux/amd64
          docker_file: prod.Dockerfile
          push: 'true'
          token: ${{ secrets.GITHUB_TOKEN }}
          extra_tag: canary
